### ISSUE TITLE
Fails with marquee text

### ISSUE THREAD

**Issue by trappedinspacetime** [sineemore/stw#10]
First of all, I congratulate you on your project. It works great except with `marquee` text.
I have below script which scrolls `rss` news feeds from right to left in terminal. But unfortunately it fails. 

     while true;do n="$(curl -s https://news.yahoo.com/rss/|sed 's/</\n/g'|grep "title>"|sed -e '/^\// d' -e 's/title>/---------- /g' -e '1,3d'|tr '\n' ' ')";for i in $(eval echo {0..${#n}});do echo -ne "\e[s\e[0;0H${n:$i:$COLUMNS}\e[u";sleep .15;printf \\033c;done;done
     
     
I couldn't wrap my head around it.

**Comment by sineemore** [comment]
Probably because stw doesn't support control sequences (color, cursor position, etc).

Your best bet is to output complete text per frame I guess.

**Comment by sineemore** [comment]
Here is a simple example:

```sh
#!/bin/bash

set -eu

pad="                    "
text="${pad}Very long text should scroll like <marquee> did.${pad}"

pad_size="${#pad}"
text_size="${#text}"

i=1
while [ $(( i + pad_size )) -le $text_size ]
do
    printf "${text:i:pad_size}"
    printf '\n\004\n'
    i=$(( i + 1 ))
    sleep 0.1
done
```

Save file as marquee.sh, make it executable and run with `stw -t -x10 -y-10 ./marquee.sh`

Notice the usage of `printf '\n\004\n'`. This line in output tells stw to render collected text and wait next frame.

https://github.com/sineemore/stw/blob/master/config.h#L26

Also, watch out for CPU usage, `sleep` command is not a builtin one. Probably it's better to write this script in Perl, Python, etc to save that forks and avoid scripting in bash :)

**Comment by sineemore** [comment]
Here is a marquee helper example in Go, you can compile it with `go build -o marquee-helper filename.go`:

```go
package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"strings"
	"time"
)

const stwFlushFrame = "\n\004\n"

func main() {
	width := flag.Int("w", 20, "output width")
	sleep := flag.Duration("s", 100*time.Millisecond, "amount of sleep after each output")
	flag.Parse()

	pad := strings.Repeat(" ", *width)

	scanner := bufio.NewScanner(os.Stdin)
	for scanner.Scan() {

		text := pad + scanner.Text() + pad
		for i := 0; i <= len(text)-len(pad); i += 1 {

			fmt.Print(text[i : i+*width])
			fmt.Print(stwFlushFrame)

			if *sleep != 0 {
				time.Sleep(*sleep)
			}
		}
	}
}
```

Try it with

```sh
stw -t -F'monospace:size=54' -bblack -flime sh -c 'seq 1 10 | ./marquee-helper -w 20 -s 10ms'
```

It runs at 100 FPS with near 0 CPU usage. At least on my machine -.-

**Comment by trappedinspacetime** [comment]
@sineemore Thank you for your help. Both of them works well, but as you stated `go` `marquee-helper` is better.  You are a good instructor. 
I still have method confusion. Shall I download `rss` feeds into a file and `cat` it to `stw`?

**Comment by sineemore** [comment]
IIUC, you need something like this:

```sh
#!/bin/sh

set -eu

# params
marquee_helper=~/x/stw-samples/marquee-helper # path to marquee-helper Go binary
width=100                                     # marquee width
sleep=100ms                                   # animation speed
update_period=$(( 60 * 60 * 1 ))              # update rss text every 1 hour

rssline() {
    curl -s https://news.yahoo.com/rss/ \
    | sed 's/</\n/g' \
    | grep "title>" \
    | sed -e '/^\// d' -e 's/title>/---------- /g' -e '1,3d' \
    | tr '\n' ' '
}

unixtime() {
    date +%s
}

text="$(rssline)"
last="$(unixtime)"

while :
do
    echo loop >&2
    now="$(unixtime)"
    if [ $(( last + update_period )) -lt "$now" ]
    then
        text="$(rssline)"
        last="$now"
        echo update >&2
    fi

    printf '%s' "$text" | "$marquee_helper" -w "$width" -s "$sleep"
done
```

Set valid params in the script and run with `stw`:

```
stw ./rss.sh
```

**Comment by trappedinspacetime** [comment]
@sineemore I am grateful for all your help. You spent time for me. It works well. 
All the best.

**Comment by trappedinspacetime** [comment]
@sineemore in `go` `marquee_helper`  text flickers now and then but I think I can handle it.

**Comment by sineemore** [comment]
Btw, while I've tested RSS script I've found, that clicks won't restart shell script immediately when it is a long running process. Fixed it in master.

Clicking stw window is a hack to immediately restart subcommand (for example to get latest RSS content in your case). I use clicks to skip waiting another minute and update `pstree` output on my desktop.

**Comment by trappedinspacetime** [comment]
@sineemore I tested your latest push. Thanks, it works well.
Regarding the flikering of the marquee text, I recorded the following clip from my screen. I haven't figured out if it's related to `marquee_helper`.

https://user-images.githubusercontent.com/1314821/150337141-38a7d917-b1b2-4f5a-ac27-499e0af4ae30.mp4

**Comment by trappedinspacetime** [comment]
Since I was not able to fix flickering issue with `marquee_helper.go` I decided  to use your `bash` way. But I hit [printf: --: invalid option](https://unix.stackexchange.com/questions/22764/dashes-in-printf) bug. Luckily replacing `printf` with `/usr/bin/printf` works around the bug.

          #!/bin/bash
          
          set -eu
          rssline() {
              curl -s https://www.gercekgundem.com/rss/ \
              | sed 's/</\n/g' \
              | grep "title>" \
              | sed -e '/^\// d' -e 's/title>/---------- /g' -e '1,3d' \
              | tr '\n' ' '
          }
          
          pad="                                                                                                                      "
          rtext="$(rssline)"     
          text="$pad$rtext$pad"            
          #text="${pad}Very long text should scroll like <marquee> did.${pad}"
          
          pad_size="${#pad}"
          text_size="${#text}"
          
          i=1
          while [ $(( i + pad_size )) -le $text_size ]
          do
              /usr/bin/printf "${text:i:pad_size}"
              /usr/bin/printf '\n\004\n'
              i=$(( i + 1 ))
              sleep 0.1
          done

**Comment by sineemore** [comment]
`printf` failed when `"${text:i:pad_size}"` evaluated to "--...". You can fix it with `printf -- "${text:i:pad_size}"`.

https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html

Check **Guideline 10** at the bottom of the page.

**Comment by trappedinspacetime** [comment]
@sineemore Thank you for the info. `bash` scripting is sometimes tricky.
