### ISSUE TITLE
floating point period cannot be set

### ISSUE THREAD

**Issue by sewnie** [sineemore/stw#12]
eg. `-p 0.3`

**Comment by sineemore** [comment]
What is your use case for milliseconds sleep?

stw spawns new process each tick, even one process per second is noticeable.

You can use delimiter char to handle sleeping more precisely within your script. Basically you `echo` your data, `echo` delimiter, sleep and continue with next frame. All can be done from a single script invocation.
https://github.com/sineemore/stw/blob/master/config.h#L26

**Comment by sewnie** [comment]
> What is your use case for milliseconds sleep?

simply to see the output of a command change instantly

**Comment by sineemore** [comment]
Sample with sleep control within script:

**fast-clock.sh**
```
#!/bin/bash

while :
do
    date +"%T.%N"
    printf '\004\n'
    sleep 0.1
done
```

Run with `$ stw -x10% -y10% ./fast-clock.sh`

**Comment by sewnie** [comment]
thanks!

you can also do 
```bash
while sleep 0.1; do
    date +"%T.%N"
    printf '\004\n'
done
```
