### ISSUE TITLE
packaging

### ISSUE THREAD

**Issue by sewnie** [sineemore/stw#13]
from the man page, i assume the maintainer is using Void linux, but this project does not have versions nor tags,

i am looking to package this for void; otherwise i suggest the maintainer does it as they seem to be using Void Linux.

**Comment by sineemore** [comment]
Feel free to package stw, I'll add first tag.

**Comment by sineemore** [comment]
https://github.com/sineemore/stw/releases/tag/0.1

**Comment by sewnie** [comment]
i do not see how the Makefile has anything to do with this,
i did see `dwm` which uses freetype2 and fontconfig having this:
```
do_build() {
	[ -e ${FILESDIR}/config.h ] && cp ${FILESDIR}/config.h config.h
	sed -i "/CFLAGS/s|\${CPPFLAGS}|& $CFLAGS|g" config.mk
	sed -i "/LDFLAGS/s|\-s|$LDFLAGS|g" config.mk
	make CC=$CC INCS="-I. -I${XBPS_CROSS_BASE}/usr/include/freetype2" LIBS="-lX11 -lXinerama -lXft -lfontconfig"
}
```
also:
```
do_configure() {
	[ -e ${FILESDIR}/config.h ] && cp ${FILESDIR}/config.h config.h
	cat <<! >>config.mk
INCS = -I${XBPS_CROSS_BASE}/usr/include/freetype2
INCS+= -I${XBPS_CROSS_BASE}/usr/include/X11
LIBS = -lc -lm -lXft -lfontconfig -lX11
!
}
```
i assume i can do this to the stw package as well.
as we can also have a custom configuration for stw via packages.

**Comment by sineemore** [comment]
Well, if it is a way to go than OK =)

**Comment by sineemore** [comment]
You can continue packaging with https://github.com/sineemore/stw/releases/tag/0.2

**Comment by sineemore** [comment]
https://github.com/void-linux/void-packages/pull/37834#issuecomment-1175143658

We should use `STWCFLAGS` and keep `CFLAGS`. Same stands for `LDFLAGS`.

Also `CC` should probably be removed.

**Comment by sewnie** [comment]
> Also CC should probably be removed.

True, but could have been replaced for `c99` instead of `cc`. 

as for the self flags:
```
cc -std=c99 -pedantic -Wall -Werror -I/usr/include/X11 `pkg-config --cflags fontconfig` -I/usr/aarch64-linux-gnu/usr/include -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=2    -fstack-clash-protection -D_FORTIFY_SOURCE=2 -O2 -pipe -march=armv8-a   -I/usr/aarch64-linux-gnu/usr/include -fdebug-prefix-map=/builddir/stw-0.2=. -c stw.c
cc1: error: bad value ('armv8-a') for '-march=' switch
cc1: note: valid arguments to '-march=' switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server cascadelake tigerlake cooperlake bonnell atom silvermont slm goldmont goldmont-plus tremont knl knm x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 znver2 btver1 btver2 native
make: *** [Makefile:8: stw.o] Error 1
=> ERROR: stw-0.2_1: do_install: '${make_cmd} STRIP=true PREFIX=/usr DESTDIR=${DESTDIR} ${make_install_args} ${make_install_target}' exited with 2
=> ERROR:   in do_install() at common/build-style/gnu-makefile.sh:40
```

**Comment by sewnie** [comment]
cool! it works. 
shall i open a new PR?
edit: that was a stupid question

**Comment by sewnie** [comment]
ehhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh its stale now and i no longer use void
