### ISSUE TITLE
root-tail like behaviour?

### ISSUE THREAD

**Issue by loosefish-scapegrace** [sineemore/stw#20]
Thanks for creating this program; it's great.

I can't figure out a way to just display text from stdin which scrolls down on a new line, like the similar program `root-tail` or just using `tail -f` in a terminal. Is there a way of doing this?

**Comment by sineemore** [comment]
Hi, stw displays text as is, there is no pagination or scrolling.

To display stdin you can run stw with /bin/cat

    ps | stw -x32 -y32 -p0 cat

In case you really want some text magic, you can check https://github.com/sineemore/stw/blob/master/config.h#L26 and try using delimeter string.

**Comment by sineemore** [comment]
related: https://github.com/sineemore/stw/issues/10
