### ISSUE TITLE
Erroneous behaviour with empty text

### ISSUE THREAD

**Issue by PrzemyslawPogorzelec** [sineemore/stw#5]
If returned text changes between empty and non-empty erroneous behaviour is observed.
`echo "1" > /tmp/1`
`stw -p 1 cat /tmp/1`
Expected text: "1" is displayed.
`echo "" > /tmp/1`
Dissapearance of text/window would be expected, but previous text is still displayed.
`echo "1" > /tmp/1`
Program crashes with:
```
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  53 (X_CreatePixmap)
  Value in failed request:  0x0
  Serial number of failed request:  54
  Current serial number in output stream:  67
```
Problem seems to be related to `window_width` in `draw` function.
Once `window_width = borderpx * 2;` is changed to `window_width = 1;` text starts to update correctly, and there are no crashes.
However, window with width of (apparently) 1px is drawn all the time, even with empty text.

**Comment by sineemore** [comment]
Done in https://github.com/sineemore/stw/commit/90f79a240d8128256272472320f625ee9d073cf7

**Comment by sineemore** [comment]
Note, I've also renamed `windowOnTop` to `window_on_top` to follow *snake_case* and changed the type to bool.
