### ISSUE TITLE
Window sometimes hangs when showing contents of a changing file

### ISSUE THREAD

**Issue by PrzemyslawPogorzelec** [sineemore/stw#6]
When using stw to `cat` actively changed file, I noticed that stw sometimes stops refreshing text window.
When this happens stw starts using up big part of CPU and stw window is frozen on some previous state of the file.

Run
`stw -p 1 cat /tmp/1`
Then run two commands:
`find /usr | tail > /tmp/1`
`find / | tail > /tmp/1`
Quite consistantly the error will occur, if not - repeat commands multiple times, rapidly.

It seems at least one of commands needs to take a lot of time (like `find / | tail`; I noticed this with one of commands being pdflatex) in order for this problem to happen.

To test this issue, I've put some printf commands around part of `stw.c` commented as "handle signals" and noticed that SIGCHLD, and SIGALRM branches stop being reached when the error occurs, while entire program seems to loop as fast as possible.

**Comment by sineemore** [comment]
Hi, @PrzemyslawPogorzelec

If the program loops and uses a great portion of CPU the problem probably resides in the `poll` syscall. You can experience similar issues when one of the `poll`'s flags haven't been handled and it will immediately exit the syscall making the program loop in the outer `while`.


I'm on a short vacation and can't run stw to test as I only have Mac right now. I'll investigate the problem in a few days, for now you can try to debug the `poll` syscall usage in stw.

**Comment by sineemore** [comment]
@PrzemyslawPogorzelec

I've actually never used stw with empty text and you've managed to find rather interesting bugs regarding this usage.
Thanks a lot! :+1:

**Comment by PrzemyslawPogorzelec** [comment]
You are welcome. Thank you for your fixes!
