### ISSUE TITLE
Alpha isn't working.

### ISSUE THREAD

**Issue by anverb** [sineemore/stw#9]
Hello. 
When I type command "stw -p 1 -x 100 -y 100 -f '#C7C7C7' -b  black -F monospace:size=30 sh -c 'echo "TEXT"'" here's text and it's OK. 
![screen1](https://user-images.githubusercontent.com/88091752/128560311-6e23f03d-f48f-4c3f-abbc-bda3ffe53cf4.png)

But if I try to use -A to get alpha "stw -p 1 -x 800 -y 500 -f '#C7C7C7' -b 'black' **-A 0** -F monospace:size=30 sh -c 'echo "ALPHA (?!) TEXT"'" there's no alpha.
![screen2](https://user-images.githubusercontent.com/88091752/128560389-fb1e3376-c3df-415e-ac94-e1204d522f44.png)

Also I tried to not use background and use alpha, but it still black rectangle at background "stw -p 1 -x 800 -y 500 -f '#C7C7C7' **-A 0** -F monospace:size=30 sh -c 'echo "WITHOUT BG SET"'"
![screen3](https://user-images.githubusercontent.com/88091752/128560405-3cab3801-cea0-4489-b4c0-1e2db46b138c.png)

How can I get transparent background? Thanks.

**Comment by sineemore** [comment]
Best bet you don't have a running X compositor. You need one to have transparency under X.

Check out picom:

https://wiki.archlinux.org/title/Picom

A running compositor is pretty much a universal requirement for transparency in X applications. You'll need one for transparent backgrounds in terminals, bars, docks and stw as well.

**Comment by anverb** [comment]
You're right, I used compton at once, but now I don't have any compositor. Thanks, I thought it'll works works fine  without it.
